version: '3'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 54320:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/headline
      - myapp_data:/headline/data
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      RAILS_ENV: production

volumes:
  db_data: {}
  myapp_data: {}
