name: "CI"
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
env:
  RUBY: '3.2.1'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        ports: ["5432:5432"]
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: headline_test
          DB_USERNAME: headline
          DB_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://headline:password@localhost:5432/headline_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Set up database
        # run: bin/rails db:create db:migrate
        run: bin/rails db:schema:load
      - name: Run tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
#       - name: Security audit dependencies
#         run: bundle exec bundler-audit --update
#       - name: Security audit application code
#         run: bundle exec brakeman -q -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
